sudo: required
language: ruby
services:
  - docker
script:
  - docker build -t "cluebotng/core:$(git rev-parse --short HEAD)" .
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "cluebotng/core:$(git rev-parse --short HEAD)"
  - if [ "$TRAVIS_BRANCH" == "master" ];
    then
      docker tag "cluebotng/core:$(git rev-parse --short HEAD)" cluebotng/core:latest &&
      docker push cluebotng/core:latest;
    fi
env:
  global:
  - secure: Xy6ralNMDhl+ICRYbYdi/ivFx7akPzWMDsfgrzb5cxXtQVIZ2LQeOXGVH3EyIMYXhox2ye4RutBOLIiYzanLZnE1p+yNKCB7x1pu4rJqDWJb05H3VIC4OZ2TTLy4oDXNBYu9kXeV+35VeYKpKdqfHqD0C+pJVLmab13rOjJR0Ck=
  - secure: lvlkAmf5QYiTkVvOO/3GBP7CFRwNOkYS+5yB7prThqm0RB77XYWLDi8UXtdW6GtUlm0cF6IaBbJ5ddS4vmtTaHiIFMrmeDvA4AgWwY2GzJ2D61TvaNVYLa5QRKQZdOdTWyj/zgtR/FNRovRZHPcyJaeP4LcMFp1X0qcumXhn70U=
