sudo: required
language: ruby
services:
  - docker
script:
  # Build docker image (also dumps bins into src/)
  - docker build -t "cluebotng/core:$(git rev-parse --short HEAD)" .
after_success:
  # Upload to docker
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "cluebotng/core:$(git rev-parse --short HEAD)"
  - if [ "$TRAVIS_BRANCH" == "master" ];
    then
      docker tag "cluebotng/core:$(git rev-parse --short HEAD)" cluebotng/core:latest &&
      docker push cluebotng/core:latest;
    fi
  # Upload to bintray
  - mkdir -p build
  - docker run -d --name cluebotng-core cluebotng/core /bin/bash
  - docker cp "cluebotng-core:/opt/cbng/core/bin/cluebotng" build/cluebotng
  - curl -T build/cluebotng -u "damianzaremba:$BINTRAY_KEY" "https://api.bintray.com/content/cluebot/cluebotng/core/$(git rev-parse --short HEAD)/cluebotng?publish=1&override=0&explode=0"
  - docker cp "cluebotng-core:/opt/cbng/core/bin/create_ann" build/create_ann
  - curl -T build/create_ann -u "damianzaremba:$BINTRAY_KEY" "https://api.bintray.com/content/cluebot/cluebotng/core/$(git rev-parse --short HEAD)/create_ann?publish=1&override=0&explode=0"
  - docker cp "cluebotng-core:/opt/cbng/core/bin/create_bayes_db" build/create_bayes_db
  - curl -T build/create_bayes_db -u "damianzaremba:$BINTRAY_KEY" "https://api.bintray.com/content/cluebot/cluebotng/core/$(git rev-parse --short HEAD)/create_bayes_db?publish=1&override=0&explode=0"
  - docker cp "cluebotng-core:/opt/cbng/core/bin/print_bayes_db" build/print_bayes_db
  - curl -T build/print_bayes_db -u "damianzaremba:$BINTRAY_KEY" "https://api.bintray.com/content/cluebot/cluebotng/core/$(git rev-parse --short HEAD)/print_bayes_db?publish=1&override=0&explode=0"
  - docker cp "cluebotng-core:/opt/cbng/core/var/bayes.db" build/bayes.db
  - curl -T build/bayes.db -u "damianzaremba:$BINTRAY_KEY" "https://api.bintray.com/content/cluebot/cluebotng/core/$(git rev-parse --short HEAD)/bayes.db?publish=1&override=0&explode=0"
  - docker cp "cluebotng-core:/opt/cbng/core/var/two_bayes.db" build/two_bayes.db
  - curl -T build/two_bayes.db -u "damianzaremba:$BINTRAY_KEY" "https://api.bintray.com/content/cluebot/cluebotng/core/$(git rev-parse --short HEAD)/two_bayes.db?publish=1&override=0&explode=0"
  - docker cp "cluebotng-core:/opt/cbng/core/var/main_ann.fann" build/main_ann.fann
  - curl -T build/main_ann.fann -u "damianzaremba:$BINTRAY_KEY" "https://api.bintray.com/content/cluebot/cluebotng/core/$(git rev-parse --short HEAD)/main_ann.fann?publish=1&override=0&explode=0"
  - docker rm -f cluebotng-core
env:
  global:
  - secure: Xy6ralNMDhl+ICRYbYdi/ivFx7akPzWMDsfgrzb5cxXtQVIZ2LQeOXGVH3EyIMYXhox2ye4RutBOLIiYzanLZnE1p+yNKCB7x1pu4rJqDWJb05H3VIC4OZ2TTLy4oDXNBYu9kXeV+35VeYKpKdqfHqD0C+pJVLmab13rOjJR0Ck=
  - secure: lvlkAmf5QYiTkVvOO/3GBP7CFRwNOkYS+5yB7prThqm0RB77XYWLDi8UXtdW6GtUlm0cF6IaBbJ5ddS4vmtTaHiIFMrmeDvA4AgWwY2GzJ2D61TvaNVYLa5QRKQZdOdTWyj/zgtR/FNRovRZHPcyJaeP4LcMFp1X0qcumXhn70U=
  - secure: IHYZRhrPpH9e60FmPzE1kp6LqeOBLR+OdRd3PYrOkiF29NXHNbqvaueoFbZNycQZ6pPsjloNxXNZv6aveOnxV2FPhkOzwf6ddLutspdn/J7KqYFkOsW4XhzGhS4jjjlHOKfokjf7vlaa3gv98EYajnXmwO8ntAigH0YLv9Tul4I=
